In [1]:
import numpy as np
import pandas as pd

1. Write a Python program to create a vector with values ranging from 10 to 49

In [2]:
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Write a Python program to reverse a vector (first element becomes last)

In [3]:
a = np.arange(10,49)
b = a[::-1]
print(b)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


3. Write a Python program to create a 3x3 matrix with values ranging from 0 to 8

In [4]:
aa = np.arange(0,9)
print(aa)
print(aa.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Write a Python program to find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
var = [1,2,0,0,4,0]
var1 = np.nonzero(var)
print(var1)

(array([0, 1, 4], dtype=int64),)


5. Write a Python program to create a 3x3x3 array with random values

In [6]:
variable1 = np.array([10,20,30,40,5,15,25,50,55])
variable2 = variable1.reshape(3,3)
print(variable2)

[[10 20 30]
 [40  5 15]
 [25 50 55]]


6. Write a Python program to create a 10x10 array with random values and find the minimum and
maximum values

In [7]:
var1 = np.arange(12,112)
var2 = var1.reshape(10,10)
print(var2)
print(var2.min())
print(var2.max())

[[ 12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41]
 [ 42  43  44  45  46  47  48  49  50  51]
 [ 52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81]
 [ 82  83  84  85  86  87  88  89  90  91]
 [ 92  93  94  95  96  97  98  99 100 101]
 [102 103 104 105 106 107 108 109 110 111]]
12
111


7. Write a Python program to create a 5x5 matrix with row values ranging from 0 to 4

In [8]:
var11 = np.zeros((5,5))
print(var11)

var11 += np.arange(5)
print(var11)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


8. Write a Python program to find the nearest value from a given value in an array.

In [12]:
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(10)
print(array)

[0.44116588 0.25298707 0.06922968 0.26248576 0.62104652 0.60671271
 0.81939563 0.85629594 0.73053314 0.54836897]


9.Write a Python program to find whether two random arrays A and B are equal.

In [9]:
A = np.array((1,2,3,5,7,9,11))
B = np.array((2,4,6,7,8,10))
print(A == B)

False


C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


10. Consider the vector [1, 2, 3, 4, 5], write a Python program to build a new vector with three
consecutive zeros interleaved between each value

In [10]:
A = [1,2,3,4,5]
B = np.zeros(17)
B[0] = A[0]
B[4] = A[1]
B[8] = A[2]
B[12] = A[3]
B[16] = A[4]

print(B)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


11. Write a Python program to find the most frequent value in an array.

In [11]:
a = np.array((11,20,22,32,12,34,56,56,67))
print(a)
print("Most frequent value in the above array:")
print(np.bincount(a).argmax())

[11 20 22 32 12 34 56 56 67]
Most frequent value in the above array:
56
