In [11]:
def func_python(N):
    d=0
    for i in range(N):
        d += (i % 3 - 1) * 1
    return d

In [24]:
import numpy as np

In [34]:
distance = [40,50,60]
speed1 = [30,35,25]
dist = np.array(distance)
speed = np.array(speed1)

time = dist/speed
print(time)

[1.33333333 1.42857143 2.4       ]


In [37]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]
print(a+b)

c = [val + 5 for val in a]
print(c)

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]
[6, 8, 10, 12, 14]


In [47]:
f = np.array((1,11,21,31))
g = np.array((2,22,32,42))
print(f+g)
print(f**2) #square of f
print(g*3)

[ 3 33 53 73]
[  1 121 441 961]
[  6  66  96 126]


In [54]:
c = np.arange((10))
print('array:       ',c)
print()

array:        [0 1 2 3 4 5 6 7 8 9]



In [56]:
anarray = np.array(np.arange(1,3,5))
print('anarray:      ',anarray)

anarray:       [1]


In [58]:
kirti = np.array(np.linspace(1,3,5))
print('anarray:      ',kirti)
type(kirti)

anarray:       [1.  1.5 2.  2.5 3. ]


numpy.ndarray

In [74]:
data = np.array((32,45,123,756,23,2123,1,2,3,4,5,6,6,5,4,3,2,1,78,89,87,76,54,31))
data.shape
data2 = data.reshape(4,6)
print(data2)
print(data2.dtype)


[[  32   45  123  756   23 2123]
 [   1    2    3    4    5    6]
 [   6    5    4    3    2    1]
 [  78   89   87   76   54   31]]
int32


In [75]:
np.zeros(40)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [77]:
np.eye(5)   #5*5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.diag(np.array([1,3,5,7,9,2,4,6]))   #diagonal elemests are filled

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 6]])

In [81]:
import pandas as pd

In [86]:
series1 = pd.Series([1,3,5,7,9,2,4,6])
print(series1)
print(series1.values)
series1.index

0    1
1    3
2    5
3    7
4    9
5    2
6    4
7    6
dtype: int64
[1 3 5 7 9 2 4 6]


RangeIndex(start=0, stop=8, step=1)

In [98]:
series2 = pd.Series([10,20,30,40,50], index=[1,2,3,4,5])
series2
print(series2[5])
series2[[0,1,2]]
print(series2 + 4)
print(series2**2)
print(series2[series2>30])
print(np.sqrt(series2))
print(np.square(series1))

50
1    14
2    24
3    34
4    44
5    54
dtype: int64
1     100
2     400
3     900
4    1600
5    2500
dtype: int64
4    40
5    50
dtype: int64
1    3.162278
2    4.472136
3    5.477226
4    6.324555
5    7.071068
dtype: float64
0     1
1     9
2    25
3    49
4    81
5     4
6    16
7    36
dtype: int64


C:\Users\hp\Anaconda3\lib\site-packages\pandas\core\series.py:942: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


In [101]:
x = [1,3,5,2,4,7]
f = lambda x:x.max() - x.min()
print(f)

<function <lambda> at 0x000002B1E0850378>
