In [49]:
import numpy as np   #numerical python

In [22]:
an_array = np.array([(1,2),(3,4),(5,6)])
print(an_array.sum(axis=1))
print(an_array.sum(axis=0))
print(an_array.reshape(2,3))
print(an_array[:2,1:])  #shape(2,2)
print(an_array[0])  
print(an_array[2,:])   #shape(3,)

[ 3  7 11]
[ 9 12]
[[1 2 3]
 [4 5 6]]
[[2]
 [4]]
[1 2]
[5 6]


In [37]:
an_array1 = np.array([(1,3,5,7,9,11),(11,13,15),(21,23,25),(31,33,35),(41,43,45),(51,53,55),(61,63,65)])
print(an_array1[0])
print(an_array[1:,1:])
print(an_array1[:2])

(1, 3, 5, 7, 9, 11)
[[4]
 [6]]
[(1, 3, 5, 7, 9, 11) (11, 13, 15)]


In [41]:
array1 = np.linspace(1,4,10)    #gives 10 values in the range(1,4)
print(array1)

[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.        ]


In [45]:
a = np.random.rand(3,7)    #gives randoms values in the form 3X7 
a

array([[0.06442553, 0.4853969 , 0.18780174, 0.00988875, 0.24805291,
        0.45290741, 0.97724362],
       [0.79811711, 0.03722107, 0.91587988, 0.11434889, 0.57957578,
        0.87907081, 0.85069296],
       [0.70450787, 0.83917455, 0.93139653, 0.11050214, 0.15582903,
        0.09612393, 0.35035132]])

In [48]:
aa = np.array(np.linspace(2,4,9))   #gives output in the form of 9 values in the range(2,4)
aa                                  # space bewteen values in linespace = (max value - initialvalue/(no. of elements)-1)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

In [51]:
import pandas as pd   # Panel Data Analysis

In [54]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [58]:
dates = pd.date_range('20130101', periods=6)  #%y-%d-%m
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [80]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.T)   #Transposed the dataframe

                   A         B         C         D
2013-01-01 -0.034925  0.638814  0.971646  1.456985
2013-01-02  0.092054  1.751999 -0.184593 -0.480449
2013-01-03 -0.354285  0.011940  0.787852 -0.731276
2013-01-04 -0.314747 -0.728111  0.883682 -0.650826
2013-01-05  1.434857 -1.945863 -1.076997 -0.012425
2013-01-06 -0.765476  0.553147 -0.484811 -0.587279
   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.034925    0.092054   -0.354285   -0.314747    1.434857   -0.765476
B    0.638814    1.751999    0.011940   -0.728111   -1.945863    0.553147
C    0.971646   -0.184593    0.787852    0.883682   -1.076997   -0.484811
D    1.456985   -0.480449   -0.731276   -0.650826   -0.012425   -0.587279


In [77]:
df2 = pd.DataFrame({'A': 1.,
                      'B': pd.Timestamp('20130102'),
                      'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                       'D': np.array([3] * 4, dtype='int32'),
                        'E': pd.Categorical(["test", "train", "test", "train"]),
                      'F': 'foo'})
print(df2)
print(df2.dtypes)
print(df2.index)
print(df2.columns)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
Int64Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [84]:
df.sort_index(axis=1,ascending=False)  #descending order of columns 

D         C         B         A
2013-01-01  1.456985  0.971646  0.638814 -0.034925
2013-01-02 -0.480449 -0.184593  1.751999  0.092054
2013-01-03 -0.731276  0.787852  0.011940 -0.354285
2013-01-04 -0.650826  0.883682 -0.728111 -0.314747
2013-01-05 -0.012425 -1.076997 -1.945863  1.434857
2013-01-06 -0.587279 -0.484811  0.553147 -0.765476

In [86]:
df.sort_values(by='C')   # sorting the column 'C' in ascending order

A         B         C         D
2013-01-05  1.434857 -1.945863 -1.076997 -0.012425
2013-01-06 -0.765476  0.553147 -0.484811 -0.587279
2013-01-02  0.092054  1.751999 -0.184593 -0.480449
2013-01-03 -0.354285  0.011940  0.787852 -0.731276
2013-01-04 -0.314747 -0.728111  0.883682 -0.650826
2013-01-01 -0.034925  0.638814  0.971646  1.456985

In [88]:
df.loc[:, 'D'] = np.array([5] * len(df))
df

A         B         C  D
2013-01-01 -0.034925  0.638814  0.971646  5
2013-01-02  0.092054  1.751999 -0.184593  5
2013-01-03 -0.354285  0.011940  0.787852  5
2013-01-04 -0.314747 -0.728111  0.883682  5
2013-01-05  1.434857 -1.945863 -1.076997  5
2013-01-06 -0.765476  0.553147 -0.484811  5

In [91]:
#To drop any rows that have missing data.
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1.dropna(how='any')

A         B         C  D    E
2013-01-01 -0.034925  0.638814  0.971646  5  1.0
2013-01-02  0.092054  1.751999 -0.184593  5  1.0

In [93]:
#Filling missing data.
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1.fillna(value=5)

A         B         C  D    E
2013-01-01 -0.034925  0.638814  0.971646  5  1.0
2013-01-02  0.092054  1.751999 -0.184593  5  1.0
2013-01-03 -0.354285  0.011940  0.787852  5  5.0
2013-01-04 -0.314747 -0.728111  0.883682  5  5.0

In [94]:
#To get the boolean mask where values are nan
df1.isna()

A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

In [100]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})
print(left)
print(right)
pd.merge(left, right, on='key')

   key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     5


key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [105]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])
print(df)

s = df.iloc[3]
print(s)

          A         B         C         D
0 -0.234748  2.708592  0.788393  0.272000
1 -0.178292  0.542294 -0.121998  0.010922
2 -1.461509  0.465720 -0.724727 -0.454224
3  0.519562 -1.531366 -1.954506 -0.189757
4  0.465296 -2.050627  0.680085 -1.393067
5  0.408230 -1.183682  0.320363  0.419792
6 -0.817307  1.042718 -0.714910 -0.611215
7  0.088480  1.308357  0.179478 -0.891545
A    0.519562
B   -1.531366
C   -1.954506
D   -0.189757
Name: 3, dtype: float64


In [107]:
df = pd.DataFrame({'A': ['one', 'one', 'two', 'three'] * 3,
                      'B': ['A', 'B', 'C'] * 4,
                       'C': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
                     'D': np.random.randn(12),
                     'E': np.random.randn(12)})
df

A  B    C         D         E
0     one  A  foo  0.197348  1.092881
1     one  B  foo -0.854862 -1.339003
2     two  C  foo  0.633530  0.799555
3   three  A  bar  0.410389  1.509815
4     one  B  bar  0.316649  0.040192
5     one  C  bar -0.415808  0.537241
6     two  A  foo  2.142885  0.189311
7   three  B  foo -0.335303  0.619947
8     one  C  foo -0.527733 -1.120501
9     one  A  bar  1.364557  0.885913
10    two  B  bar -1.373878  0.422044
11  three  C  bar  1.110156  0.201558

In [108]:
#We can produce pivot tables from this data very easily:

pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])


C             bar       foo
A     B                    
one   A  1.364557  0.197348
      B  0.316649 -0.854862
      C -0.415808 -0.527733
three A  0.410389       NaN
      B       NaN -0.335303
      C  1.110156       NaN
two   A       NaN  2.142885
      B -1.373878       NaN
      C       NaN  0.633530

In [109]:
#CSV
#Writing to a csv file
#df.to_csv('foo.csv')
